import { Poppins } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/navbar/NavBar'

const poppins = Poppins({ 
  weight: ['100', '200', '300', '400', '600', '800'],
  subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NavBar/>
        {children}
        </body>
    </html>
  )
}
